### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by LordDamionDevil** [zackradisic/node-soundcloud-downloader#1]
I think you should include a tiny guide on how to use with Discord.JS.

i.e get file, play it and clear it after the file has been played.

even though I think adding a way to stream the audio directly via a link would be better(which is basically already on your to-do list)

**Comment by zackradisic** [comment]
Thanks for the suggestion, I added a sample with Discord.js in the readme e6a20e8d2d59900b9b47a52fbbf2cde14ad1d3e1

`scdl(url, clientId)` returns a ReadableStream so you can directly supply it as a parameter to Discord.js [see here](https://discord.js.org/#/docs/main/stable/class/VoiceConnection?scrollTo=play), no need to write to a file :)
