### ISSUE TITLE
Error 404 on all links with opus format

### ISSUE THREAD

**Issue by eritislami** [zackradisic/node-soundcloud-downloader#15]
Hey, i started using your module in my bot after your pull request which was version 0.0.9 of your project, currently that  version is working fine but after trying to update to 0.1.2 and refactor for the new changes i get error 404 on all links from the download method

I tested with this example

```js
const scdl = require("soundcloud-downloader");
let url = "https://soundcloud.com/marcelonunes-2/pearl-jam-yellow-led-better";

const info = await scdl.getInfo(url, SOUNDCLOUD_CLIENT_ID);
const opus = scdl.filterMedia(info.media.transcodings, { format: scdl.FORMATS.OPUS });
stream = await scdl.download(opus[0].url, SOUNDCLOUD_CLIENT_ID);
```

I tried different songs and all are rejecting with error 404

Environment:
- Node.js v12.16.1
- MacOS 10.15.5
- "soundcloud-downloader": "^0.1.2"

**Comment by zackradisic** [comment]
You can do the following now:
```javascript
scdl.downloadFormat(url, scdl.FORMATS.OPUS, process.env.CLIENT_ID)
  .then(stream => stream.pipe(fs.createWriteStream('audio.mp3')))
  .catch(err => console.log(err))
```

**Comment by eritislami** [comment]
Thanks
