### ISSUE TITLE
status code 404

### ISSUE THREAD

**Issue by LordDamionDevil** [zackradisic/node-soundcloud-downloader#2]
I have started to get 404 forbidden when i tried it out now.
EDIT: turns out certain songs don't work and will result in a 404 an example is:
https://soundcloud.com/the1975/tootimetootimetootime

**Comment by zackradisic** [comment]
It looks like the problem was that there are some Soundcloud songs that only have media links for for streaming via HLS protocol, and this package I only wrote to support progressive download links.

I updated the code to support HLS and I tested it with the link you provided and some others and things seem to be working fine now. You can update the npm package and see for yourself.

**Comment by LordDamionDevil** [comment]
> It looks like the problem was that there are some Soundcloud songs that only have media links for for streaming via HLS protocol, and this package I only wrote to support progressive download links.
> 
> I updated the code to support HLS and I tested it with the link you provided and some others and things seem to be working fine now. You can update the npm package and see for yourself.

I have now updated it which resulted in it breaking completely due to it not being able to find a module it uses (this also happens on a fresh install of the module)

"Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'"

**Comment by zackradisic** [comment]
Thanks, I added the @babel/runtime to the package.json

I changed it so you should use `scdl.download(url, clientid)` instead of `scdl(url, clientid)` now. Sorry, forgot to update the readme

**Comment by LordDamionDevil** [comment]
> Thanks, I added the @babel/runtime to the package.json
> 
> I changed it so you should use `scdl.download(url, clientid)` instead of `scdl(url, clientid)` now. Sorry, forgot to update the readme

Did you ever think about adding a way to get the track image, song name and artist name, url and image as I think that would be useful for music bots which want to use a Embed for showing the song that is playing or for the queue

**Comment by zackradisic** [comment]
Haven't thought about it but it seems like a good idea, I'll add it to the todo list and start working on it

**Comment by zackradisic** [comment]
@LordDamionDevil track info can now be retrieved using `scdl.getInfo(url, clientID)`. There's a good amount of helpful data in the response. Thanks for the suggestion, in the future though please post feature requests in separate issues.
