### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by BlazeIsClone** [zackradisic/node-soundcloud-downloader#28]
![image](https://user-images.githubusercontent.com/64116737/98999979-9ca2ca80-255e-11eb-8425-f0460fae06fd.png)

I did managed to fix this issue by downgrading to previous version.

**Comment by supergrov3r** [comment]
Can confirm this issue in 0.1.9 as well.

Adding `SAVE_CLIENT_ID: false` to your environmental variables will get around this issue/error.

**Comment by zackradisic** [comment]
My bad, made the fix but forgot to build...

Just published v0.2.0 should be fine.
