### ISSUE TITLE
More information about a track.

### ISSUE THREAD

**Issue by TheMaestro0** [zackradisic/node-soundcloud-downloader#4]
Is there any ability to add more information about a track, such as an image, time, Age, etc ... ?!

**Comment by zackradisic** [comment]
`scdl.getInfo(url, clientID)` returns a JSON object with track information. It contains the information you are looking for:
```javascript
const trackInfo = await scdl.getInfo(url, clientID)
trackInfo.artwork_url // image
trackInfo.duration // time in milliseconds
trackInfo.created_at // you can find the age with this
```

**Comment by TheMaestro0** [comment]
Oh Perfect, Thanks :)
